alias ea='vim ~/.bash_aliases'
alias sa='source ~/.bash_aliases'
alias eb='vim ~/.bashrc'
alias sb='source ~/.bashrc'
alias ev='vim ~/.vimrc'
alias l='ls -ls --color'
alias ll='ls -lsa --color'
alias lll='ls -ls --color; pwd'
alias ghl='git log --pretty=format:"%h - %an, %ar : %s"'
