alias ea='vim ~/.bash_aliases'
alias sa='source ~/.bash_aliases'
alias eb='vim ~/.bashrc'
alias sb='source ~/.bashrc'
alias ev='vim ~/.vimrc'
alias l='ls -lsG'
alias ll='ls -lsaG'
alias lll='ls -lsG; pwd'
alias ghl='git log --pretty=format:"%h - %an, %ar : %s"'
